### 第1题
编写一个书类：Book
（1）属性：name（字符串）、authors（字符串列表）、press（字符串）
（2）方法：print_info，输出书的信息

由Book派生出一个电子书类：ElectricBook
（1）额外属性：apps（字符串列表，可用于打开这个电子书的app名称）
（2）重写print_info
（3）readable函数：传入一个app_name，判断能否读取这本电子书

In [1]:
class Book:
    def __init__(self, name, authors, press):
        self.name = name
        self.authors = authors
        self.press = press
    
    def print_info(self):
        print(f"书名: {self.name}, 作者: {', '.join(self.authors)}, 出版社: {self.press}")

class ElectricBook(Book):
    def __init__(self, name, authors, press, apps):
        super().__init__(name, authors, press)
        self.apps = apps
        
    def print_info(self):
        super().print_info()
        print(f"支持的App: {', '.join(self.apps)}")
        
    def readable(self, app_name):
        return app_name in self.apps

# --- 测试代码 ---
book = Book("Python基础", ["张三", "李四"], "清华大学出版社")
book.print_info()

print('-' * 20)
ebook = ElectricBook("Python进阶", ["王五"], "北京大学出版社", ["Kindle", "微信读书", "Apple Books"])
ebook.print_info()
print(f"Kindle可以读取吗? {ebook.readable('Kindle')}")
print(f"Notepad可以读取吗? {ebook.readable('Notepad')}")

书名: Python基础, 作者: 张三, 李四, 出版社: 清华大学出版社
--------------------
书名: Python进阶, 作者: 王五, 出版社: 北京大学出版社
支持的App: Kindle, 微信读书, Apple Books
Kindle可以读取吗? True
Notepad可以读取吗? False


### 第2题
编写一个人员信息类PersonInfo，包含：
（1）name
（2）age
（3）job
（4）birthday
（5）readable（'on'或者'off'，默认'off'）

要求通过设定readable，可以对外部显示信息（'on'），或拒绝访问（'off'），这个设定只能通过类的成员函数完成，并且在设定前提示输入出生日期，能对应的上才可以进行修改
请你设计PersonInfo这个类，你可以自己编写合适的函数，并通过如下对象进行测试：
`person = PersonInfo('Jim', 18, 'Student', '2007-01-01')`

In [ ]:
class PersonInfo:
    def __init__(self, name, age, job, birthday):
        self.name = name
        self.age = age
        self.job = job
        self.birthday = birthday
        self.__readable = 'off'  # 设为私有属性，不允许外部直接修改
        
    def set_readable(self, status):
        if status not in ['on', 'off']:
            print("状态只能是 'on' 或 'off'")
            return
            
        input_birthday = input("请输入出生日期(YYYY-MM-DD)以验证权限: ")
        if input_birthday == self.birthday:
            self.__readable = status
            print(f"权限已修改为: {self.__readable}")
        else:
            print("出生日期验证失败，无法修改权限！")
            
    def display_info(self):
        if self.__readable == 'on':
            print(f"姓名: {self.name}, 年龄: {self.age}, 职业: {self.job}, 出生日期: {self.birthday}")
        else:
            print("拒绝访问：没有查看权限。")

# --- 测试代码 ---
person = PersonInfo('Jim', 18, 'Student', '2007-01-01')
person.display_info()           # 默认off，应该拒绝访问

print("\n--- 尝试修改权限 ---")
# 提示：运行此单元格时需要输入，建议输入 '2007-01-01' 以测试成功情况
person.set_readable('on')       
person.display_info()           # 如果上一步输入正确，这里将显示信息

### 第3题
编写一个MyFraction类，包含numerator和denominator两个属性，分别代表分数的 分子和分母，请编写如下函数：
（1）simplify：化简，去除分子、分母的公约数；
（2）重载加、减、乘、除运算

In [ ]:
import math

class MyFraction:
    def __init__(self, numerator, denominator):
        if denominator == 0:
            raise ValueError("分母不能为0")
        self.numerator = numerator
        self.denominator = denominator
        self.simplify()  # 初始化时自动化简
        
    def simplify(self):
        gcd = math.gcd(self.numerator, self.denominator)
        self.numerator //= gcd
        self.denominator //= gcd
        # 保证负号在分子上
        if self.denominator < 0:
            self.numerator = -self.numerator
            self.denominator = -self.denominator
            
    def __add__(self, other):
        new_num = self.numerator * other.denominator + other.numerator * self.denominator
        new_den = self.denominator * other.denominator
        return MyFraction(new_num, new_den)
        
    def __sub__(self, other):
        new_num = self.numerator * other.denominator - other.numerator * self.denominator
        new_den = self.denominator * other.denominator
        return MyFraction(new_num, new_den)
        
    def __mul__(self, other):
        new_num = self.numerator * other.numerator
        new_den = self.denominator * other.denominator
        return MyFraction(new_num, new_den)
        
    def __truediv__(self, other):
        if other.numerator == 0:
            raise ValueError("除数不能为0")
        new_num = self.numerator * other.denominator
        new_den = self.denominator * other.numerator
        return MyFraction(new_num, new_den)
        
    def __str__(self):
        if self.denominator == 1:
            return str(self.numerator)
        return f"{self.numerator}/{self.denominator}"

# --- 测试代码 ---
f1 = MyFraction(1, 2)
f2 = MyFraction(1, 3)
print(f"{f1} + {f2} = {f1 + f2}")
print(f"{f1} - {f2} = {f1 - f2}")
print(f"{f1} * {f2} = {f1 * f2}")
print(f"{f1} / {f2} = {f1 / f2}")

### 第6题
有一个数组：`arr0 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]`，如何得到如下数组：
`arr1 = [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], ...]`

In [ ]:
arr0 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

window_size = 4

arr1 = [arr0[i : i+window_size] for i in range(len(arr0) - window_size + 1)]

# --- 测试代码 ---
print("结果数组 arr1:")
for sub_list in arr1:
    print(sub_list)

### 第7题
创建一个形状为5X3的值在[0, 100]之间的随机数组（整数），计算并输出每一行的最大值、最小值和平均值，不能使用循环。

In [2]:
import numpy as np

arr = np.random.randint(0, 101, size=(5, 3))
print("随机生成的 5x3 数组：\n", arr)

# axis=1 表示沿着列的方向计算，得到每一行的统计值
row_max = arr.max(axis=1)
row_min = arr.min(axis=1)
row_mean = arr.mean(axis=1)

# --- 测试代码 ---
print("\n【计算结果】")
print("每一行的最大值: ", row_max)
print("每一行的最小值: ", row_min)
np.set_printoptions(precision=2, suppress=True)
print("每一行的平均值: ", row_mean)

随机生成的 5x3 数组：
 [[56 67 16]
 [ 2 53 53]
 [ 2 41 27]
 [71 82 36]
 [85 30 87]]

【计算结果】
每一行的最大值:  [67 53 41 82 87]
每一行的最小值:  [16  2  2 36 30]
每一行的平均值:  [46.33 36.   23.33 63.   67.33]
